version: '3'


services:

  billdb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'billdb'
      MYSQL_USER: 'billing'
      MYSQL_PASSWORD: 'billing1password'
      MYSQL_ROOT_PASSWORD: 'root1password'
    
    volumes:
      - billing-db:/var/lib/mysql
      - ./dump-db:/dump-db
    



  billapi:
      build: .
      ports:
        - "8085:5000"

      environment:
        MYSQL_DATABASE: 'billdb'
        MYSQL_USER: 'billing'
        MYSQL_PASSWORD: 'billing1password'
        MYSQL_ROOT_PASSWORD: 'root1password'
        MYSQL_PORT: '3306'
        MYSQL_HOST: 'billdb'

      depends_on:
        - billdb
      
      







volumes:
  billing-db:


networks:
  defualt:
    name: backend
    external: true



# version: "3"
# services:
#   app:
#     build: .
#     links:
#       - db
#     ports:
#       - "5000:5000"